# Generated by Django 4.2.9 on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('supports_refunds', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(default=dict)),
                ('confirmation_code', models.CharField(blank=True, max_length=20)),
                ('ussd_session_id', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money', to='payments.Payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_money.mobilemoneyprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_money_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_type', models.CharField(choices=[('ussd', 'USSD Code'), ('sms', 'SMS Code'), ('app', 'In-App Verification')], max_length=20)),
                ('verification_code', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='mobile_money.moneymoneypayment')),
            ],
        ),
    ]
