# Generated by Django 6.0.3 on 2026-03-19 07:13

from django.db import migrations, models
from django.conf import settings


def create_default_mobile_money_providers(apps, schema_editor):
    """Create default mobile money providers"""
    from mobile_money.models import MobileMoneyProvider
    
    providers_data = [
        {
            'name': 'MTN Mobile Money',
            'code': 'MTN_MOMO',
            'display_name': 'MTN MoMo',
            'api_endpoint': 'https://momoapi.mtn.co.ug',
            'supports_ussd': True,
            'supports_app': True,
            'min_amount': 1000,
            'max_amount': 5000000,
            'daily_limit': 10000000,
            'transaction_fee_percentage': 2.5,
            'fixed_fee': 500,
        },
        {
            'name': 'Airtel Money',
            'code': 'AIRTEL_MONEY',
            'display_name': 'Airtel Money',
            'api_endpoint': 'https://money.airtel.com',
            'supports_ussd': True,
            'supports_app': True,
            'min_amount': 1000,
            'max_amount': 4000000,
            'daily_limit': 8000000,
            'transaction_fee_percentage': 2.0,
            'fixed_fee': 400,
        },
        {
            'name': 'Stanbic Mobile',
            'code': 'STANBIC_MOBILE',
            'display_name': 'Stanbic Mobile Banking',
            'api_endpoint': 'https://mobile.stanbicbank.co.ug',
            'supports_ussd': True,
            'supports_app': True,
            'min_amount': 5000,
            'max_amount': 10000000,
            'daily_limit': 20000000,
            'transaction_fee_percentage': 1.5,
            'fixed_fee': 1000,
        },
        {
            'name': 'Centenary Mobile',
            'code': 'CENTENARY_MOBILE',
            'display_name': 'CenteMobile',
            'api_endpoint': 'https://mobile.centenarybank.co.ug',
            'supports_ussd': True,
            'supports_app': True,
            'min_amount': 2000,
            'max_amount': 7000000,
            'daily_limit': 15000000,
            'transaction_fee_percentage': 2.0,
            'fixed_fee': 800,
        },
        {
            'name': 'DFCU Mobile',
            'code': 'DFCU_MOBILE',
            'display_name': 'DFCU Mobile',
            'api_endpoint': 'https://mobile.dfcuBank.co.ug',
            'supports_ussd': True,
            'supports_app': True,
            'min_amount': 3000,
            'max_amount': 8000000,
            'daily_limit': 12000000,
            'transaction_fee_percentage': 1.8,
            'fixed_fee': 600,
        },
    ]
    
    for provider_data in providers_data:
        MobileMoneyProvider.objects.get_or_create(
            code=provider_data['code'],
            defaults=provider_data
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField(blank=True)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('supports_ussd', models.BooleanField(default=False)),
                ('supports_app', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=5000000, max_digits=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=10000000, max_digits=10)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=500, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(default=dict)),
                ('confirmation_code', models.CharField(blank=True, max_length=20)),
                ('ussd_session_id', models.CharField(blank=True, max_length=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=models.CASCADE, related_name='mobile_money', to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=models.PROTECT, to='mobile_money.mobilemoneyprovider')),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_type', models.CharField(choices=[('ussd', 'USSD Code'), ('sms', 'SMS Code'), ('app', 'In-App Verification')], max_length=20)),
                ('verification_code', models.CharField(max_length=10)),
                ('ussd_code', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=models.CASCADE, to='mobile_money.mobilemoneyprovider')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('verification_sent', 'Verification Sent'), ('verification_completed', 'Verification Completed'), ('ussd_session', 'USSD Session')], max_length=30)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=models.CASCADE, to='mobile_money.mobilemoneyprovider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='mobile_money.mobilemoneypayment')),
            ],
        ),
        migrations.RunPython(create_default_mobile_money_providers),
    ]
