# Generated by Django 6.0.3 on 2026-04-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_money', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilemoneyprovider',
            options={'ordering': ['display_name']},
        ),
    ]
