# Generated by Django

import re
import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def provider_code(provider):
    base = provider.display_name or provider.name or f"PROVIDER_{provider.pk}"
    code = re.sub(r'[^A-Z0-9]+', '_', base.upper()).strip('_')
    return code[:20] or f"PROVIDER_{provider.pk}"


def backfill_mobile_money_providers(apps, schema_editor):
    MobileMoneyProvider = apps.get_model('mobile_money', 'MobileMoneyProvider')
    used_codes = set()

    for provider in MobileMoneyProvider.objects.all():
        code = provider.code or provider_code(provider)
        original_code = code
        suffix = 1
        while code in used_codes or MobileMoneyProvider.objects.exclude(pk=provider.pk).filter(code=code).exists():
            suffix_text = f"_{suffix}"
            code = f"{original_code[:20 - len(suffix_text)]}{suffix_text}"
            suffix += 1

        provider.code = code
        used_codes.add(code)
        provider.save(update_fields=['code'])


def backfill_mobile_money_payments(apps, schema_editor):
    MobileMoneyPayment = apps.get_model('mobile_money', 'MobileMoneyPayment')
    seen_transaction_ids = set()

    for mobile_payment in MobileMoneyPayment.objects.all():
        transaction_id = mobile_payment.transaction_id or ''
        if not transaction_id or transaction_id in seen_transaction_ids:
            transaction_id = f"MM-{mobile_payment.pk}-{uuid.uuid4().hex[:12].upper()}"
        seen_transaction_ids.add(transaction_id)

        if mobile_payment.fee_amount is None:
            mobile_payment.fee_amount = Decimal('0.00')

        if mobile_payment.net_amount is None:
            mobile_payment.net_amount = mobile_payment.amount - mobile_payment.fee_amount

        mobile_payment.transaction_id = transaction_id
        mobile_payment.save(update_fields=['transaction_id', 'fee_amount', 'net_amount'])


def backfill_mobile_money_verifications(apps, schema_editor):
    MobileMoneyVerification = apps.get_model('mobile_money', 'MobileMoneyVerification')

    for verification in MobileMoneyVerification.objects.select_related('payment'):
        payment = getattr(verification, 'payment', None)
        if not payment:
            verification.delete()
            continue

        verification.user_id = getattr(payment, 'user_id', None)
        verification.provider_id = getattr(payment, 'provider_id', None)
        verification.phone_number = verification.phone_number or getattr(payment, 'phone_number', '')

        if not verification.user_id or not verification.provider_id or not verification.phone_number:
            verification.delete()
            continue

        verification.save(update_fields=['user', 'provider', 'phone_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_money', '0002_alter_mobilemoneyprovider_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilemoneyprovider',
            old_name='api_key',
            new_name='api_key_encrypted',
        ),
        migrations.RenameField(
            model_name='mobilemoneyprovider',
            old_name='max_transaction_amount',
            new_name='max_amount',
        ),
        migrations.RenameField(
            model_name='mobilemoneyprovider',
            old_name='min_transaction_amount',
            new_name='min_amount',
        ),
        migrations.RenameField(
            model_name='mobilemoneypayment',
            old_name='reference_number',
            new_name='external_reference',
        ),
        migrations.RenameField(
            model_name='mobilemoneyverification',
            old_name='attempts',
            new_name='verification_attempts',
        ),
        migrations.AddField(
            model_name='mobilemoneyprovider',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobilemoneyprovider',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=10),
        ),
        migrations.AddField(
            model_name='mobilemoneyprovider',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
        migrations.AddField(
            model_name='mobilemoneyprovider',
            name='supports_app',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mobilemoneyprovider',
            name='supports_ussd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobilemoneypayment',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilemoneyverification',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_money.mobilemoneyprovider'),
        ),
        migrations.AddField(
            model_name='mobilemoneyverification',
            name='ussd_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mobilemoneyverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mobilemoneyprovider',
            name='api_endpoint',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneyprovider',
            name='api_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneyprovider',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=5000000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobilemoneyprovider',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobilemoneypayment',
            name='external_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='mobilemoneyprovider',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyprovider',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyprovider',
            name='supports_refunds',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyprovider',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyprovider',
            name='webhook_secret',
        ),
        migrations.RemoveField(
            model_name='mobilemoneypayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mobilemoneypayment',
            name='failure_reason',
        ),
        migrations.RunPython(backfill_mobile_money_providers, migrations.RunPython.noop),
        migrations.RunPython(backfill_mobile_money_payments, migrations.RunPython.noop),
        migrations.RunPython(backfill_mobile_money_verifications, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='mobilemoneypayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mobilemoneyverification',
            name='payment',
        ),
        migrations.AlterField(
            model_name='mobilemoneyprovider',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneypayment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneyverification',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_money.mobilemoneyprovider'),
        ),
        migrations.AlterField(
            model_name='mobilemoneyverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MobileMoneyTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('verification_sent', 'Verification Sent'), ('verification_completed', 'Verification Completed'), ('ussd_session', 'USSD Session')], max_length=30)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_money.mobilemoneyprovider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile_money.mobilemoneypayment')),
            ],
        ),
    ]
