# Generated by Django 6.0.3 on 2026-03-19 09:53

from django.db import migrations, models
from django.conf import settings


def create_default_ussd_menu(apps, schema_editor):
    """Create default USSD menu structure"""
    USSDMenuItem = apps.get_model('ussd', 'USSDMenuItem')
    
    # Main menu
    main_menu, created = USSDMenuItem.objects.get_or_create(
        screen_id='main_menu',
        defaults={
            'title': 'RentHu Uganda - Main Menu',
            'description': 'Find your perfect accommodation',
            'options': [
                {'id': '1', 'text': 'Search Hostels', 'screen': 'search_menu'},
                {'id': '2', 'text': 'Book Room', 'screen': 'quick_book'},
                {'id': '3', 'text': 'My Bookings', 'screen': 'my_bookings'},
                {'id': '4', 'text': 'My Profile', 'screen': 'profile_menu'},
                {'id': '5', 'text': 'Help & Support', 'screen': 'help_menu'},
                {'id': '0', 'text': 'Exit', 'screen': 'exit'},
            ],
            'action_type': 'menu'
        }
    )
    
    # Search menu
    search_menu, created = USSDMenuItem.objects.get_or_create(
        screen_id='search_menu',
        defaults={
            'title': 'Search Hostels',
            'description': 'Find accommodation by location',
            'options': [
                {'id': '1', 'text': 'By Location', 'screen': 'search_location'},
                {'id': '2', 'text': 'By Price', 'screen': 'search_price'},
                {'id': '3', 'text': 'By University', 'screen': 'search_university'},
                {'id': '4', 'text': 'Popular Areas', 'screen': 'popular_areas'},
                {'id': '0', 'text': 'Back', 'screen': 'main_menu'},
            ],
            'action_type': 'menu'
        }
    )
    
    # Search by location
    search_location, created = USSDMenuItem.objects.get_or_create(
        screen_id='search_location',
        defaults={
            'title': 'Enter Location',
            'description': 'Type location (e.g., Kampala, Makerere)',
            'requires_input': True,
            'input_type': 'text',
            'input_placeholder': 'Enter location',
            'input_validation': {'min_length': 2, 'max_length': 50},
            'action_type': 'search',
            'action_data': {'search_type': 'location'}
        }
    )
    
    # Search by price
    search_price, created = USSDMenuItem.objects.get_or_create(
        screen_id='search_price',
        defaults={
            'title': 'Enter Price Range',
            'description': 'Enter max price (e.g., 150000)',
            'requires_input': True,
            'input_type': 'amount',
            'input_placeholder': 'Enter max price in UGX',
            'input_validation': {'min_value': 0, 'max_value': 5000000},
            'action_type': 'search',
            'action_data': {'search_type': 'price'}
        }
    )
    
    # Search by university
    search_university, created = USSDMenuItem.objects.get_or_create(
        screen_id='search_university',
        defaults={
            'title': 'Select University',
            'description': 'Choose your university',
            'options': [
                {'id': '1', 'text': 'Makerere University', 'screen': 'search_results', 'data': {'university': 'makerere'}},
                {'id': '2', 'text': 'Kyambogo University', 'screen': 'search_results', 'data': {'university': 'kyambogo'}},
                {'id': '3', 'text': 'Bugema University', 'screen': 'search_results', 'data': {'university': 'bugema'}},
                {'id': '4', 'text': 'UCU', 'screen': 'search_results', 'data': {'university': 'ucu'}},
                {'id': '5', 'text': 'MUST', 'screen': 'search_results', 'data': {'university': 'must'}},
                {'id': '0', 'text': 'Back', 'screen': 'search_menu'},
            ],
            'action_type': 'menu'
        }
    )
    
    # Search results
    search_results, created = USSDMenuItem.objects.get_or_create(
        screen_id='search_results',
        defaults={
            'title': 'Search Results',
            'description': 'Available properties',
            'action_type': 'search',
            'paginate': True,
            'max_text_length': 140
        }
    )
    
    # My bookings
    my_bookings, created = USSDMenuItem.objects.get_or_create(
        screen_id='my_bookings',
        defaults={
            'title': 'My Bookings',
            'description': 'View your booking status',
            'action_type': 'my_bookings',
            'paginate': True
        }
    )
    
    # Profile menu
    profile_menu, created = USSDMenuItem.objects.get_or_create(
        screen_id='profile_menu',
        defaults={
            'title': 'My Profile',
            'description': 'Manage your account',
            'options': [
                {'id': '1', 'text': 'My Details', 'screen': 'profile_details'},
                {'id': '2', 'text': 'Language', 'screen': 'language_settings'},
                {'id': '3', 'text': 'Notifications', 'screen': 'notification_settings'},
                {'id': '0', 'text': 'Back', 'screen': 'main_menu'},
            ],
            'action_type': 'menu'
        }
    )
    
    # Help menu
    help_menu, created = USSDMenuItem.objects.get_or_create(
        screen_id='help_menu',
        defaults={
            'title': 'Help & Support',
            'description': 'Get help with your booking',
            'options': [
                {'id': '1', 'text': 'FAQ', 'screen': 'faq'},
                {'id': '2', 'text': 'Contact Support', 'screen': 'contact_support'},
                {'id': '3', 'text': 'Report Issue', 'screen': 'report_issue'},
                {'id': '0', 'text': 'Back', 'screen': 'main_menu'},
            ],
            'action_type': 'menu'
        }
    )
    
    # Exit screen
    exit_screen, created = USSDMenuItem.objects.get_or_create(
        screen_id='exit',
        defaults={
            'title': 'Thank You!',
            'description': 'Visit us at www.renthu.ug or call +256 123 456 789',
            'action_type': 'exit'
        }
    )
    
    # Set back navigation
    search_menu.back_screen = main_menu
    search_location.back_screen = search_menu
    search_price.back_screen = search_menu
    search_university.back_screen = search_menu
    profile_menu.back_screen = main_menu
    help_menu.back_screen = main_menu
    
    # Save all
    main_menu.save()
    search_menu.save()
    search_location.save()
    search_price.save()
    search_university.save()
    search_results.save()
    my_bookings.save()
    profile_menu.save()
    help_menu.save()
    exit_screen.save()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('current_screen', models.CharField(default='main_menu', max_length=50)),
                ('session_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('timeout', 'Timeout'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='ussd_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USSDMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('requires_input', models.BooleanField(default=False)),
                ('input_type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('phone', 'Phone Number'), ('email', 'Email'), ('amount', 'Amount')], max_length=20)),
                ('input_placeholder', models.CharField(blank=True, max_length=100)),
                ('input_validation', models.JSONField(default=dict)),
                ('action_type', models.CharField(choices=[('menu', 'Show Menu'), ('search', 'Search Properties'), ('book', 'Book Property'), ('my_bookings', 'My Bookings'), ('profile', 'User Profile'), ('help', 'Help/Support'), ('exit', 'Exit'), ('authenticate', 'Authenticate'), ('input', 'Process Input')], default='menu', max_length=50)),
                ('action_data', models.JSONField(default=dict)),
                ('max_text_length', models.PositiveIntegerField(default=160)),
                ('paginate', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSDRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('request_text', models.CharField(max_length=500)),
                ('response_text', models.TextField()),
                ('response_screen', models.CharField(max_length=50)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='requests', to='ussd.ussdsession')),
            ],
        ),
        migrations.CreateModel(
            name='USSDUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('last_session', models.DateTimeField(blank=True, null=True)),
                ('favorite_properties', models.JSONField(default=list)),
                ('quick_search_location', models.CharField(blank=True, max_length=100)),
                ('quick_search_price_range', models.CharField(blank=True, max_length=50)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('booking_confirmations', models.BooleanField(default=True)),
                ('payment_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='ussd_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='USSDPropertyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('price_display', models.CharField(max_length=30)),
                ('location_display', models.CharField(max_length=50)),
                ('contact_display', models.CharField(max_length=30)),
                ('keywords', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='ussd_properties', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='USSDBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=200)),
                ('confirmed_via_ussd', models.BooleanField(default=False)),
                ('confirmation_code', models.CharField(blank=True, max_length=10)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('status_updates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='ussd_booking', to='bookings.booking')),
                ('session', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='bookings', to='ussd.ussdsession')),
                ('property_selected', models.ForeignKey(on_delete=models.deletion.SET_NULL, null=True, related_name='ussd_bookings', to='properties.property')),
            ],
        ),
        migrations.RunPython(create_default_ussd_menu),
    ]
