# Generated by Django 6.0.3 on 2026-04-24 05:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_city_remove_property_locality_and_more'),
        ('ussd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdmenuitem',
            name='back_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_from', to='ussd.ussdmenuitem'),
        ),
        migrations.AddField(
            model_name='ussdmenuitem',
            name='parent_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ussd.ussdmenuitem'),
        ),
        migrations.AlterField(
            model_name='ussdpropertycache',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
