# Generated by Django 4.2.7 on 2026-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
