# Generated by Django 6.0.3 on 2026-04-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_total_days_alter_booking_total_months'),
        ('properties', '0002_remove_property_city_remove_property_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.room'),
        ),
    ]
