# Generated by Django 6.0.3 on 2026-04-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('bookings', '0002_alter_booking_total_days_alter_booking_total_months'),
        ('maintenance', '0002_create_default_categories'),
        ('payments', '0001_initial'),
        ('properties', '0002_remove_property_city_remove_property_locality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('check_in_reminder', 'Check-in Reminder'), ('check_out_reminder', 'Check-out Reminder'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('review_received', 'Review Received'), ('commission_paid', 'Commission Paid'), ('maintenance_request_created', 'Maintenance Request Created'), ('maintenance_status_update', 'Maintenance Status Updated'), ('maintenance_assigned', 'Maintenance Assigned'), ('maintenance_comment', 'New Maintenance Comment'), ('maintenance_property_update', 'Property Maintenance Update'), ('maintenance_completed', 'Maintenance Completed'), ('maintenance_urgent', 'Urgent Maintenance Request'), ('agent_request_assigned', 'Agent Request Assigned'), ('agent_request_completed', 'Agent Request Completed'), ('agent_new_review', 'New Agent Review'), ('agent_commission_earned', 'Commission Earned'), ('agent_profile_verified', 'Agent Profile Verified')], max_length=30, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('booking_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('property_updates', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('check_in_reminder', 'Check-in Reminder'), ('check_out_reminder', 'Check-out Reminder'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('review_received', 'Review Received'), ('commission_paid', 'Commission Paid'), ('maintenance_request_created', 'Maintenance Request Created'), ('maintenance_status_update', 'Maintenance Status Updated'), ('maintenance_assigned', 'Maintenance Assigned'), ('maintenance_comment', 'New Maintenance Comment'), ('maintenance_property_update', 'Property Maintenance Update'), ('maintenance_completed', 'Maintenance Completed'), ('maintenance_urgent', 'Urgent Maintenance Request'), ('agent_request_assigned', 'Agent Request Assigned'), ('agent_request_completed', 'Agent Request Completed'), ('agent_new_review', 'New Agent Review'), ('agent_commission_earned', 'Commission Earned'), ('agent_profile_verified', 'Agent Profile Verified')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App')], default='in_app', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('agent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agentrequest')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerequest')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
