# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(
                choices=[
                    ('email', 'Email'),
                    ('sms', 'SMS'),
                    ('push', 'Push Notification'),
                    ('in_app', 'In-App'),
                ],
                default='in_app',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('booking_confirmed', 'Booking Confirmed'),
                    ('booking_cancelled', 'Booking Cancelled'),
                    ('payment_completed', 'Payment Completed'),
                    ('payment_failed', 'Payment Failed'),
                    ('check_in_reminder', 'Check-in Reminder'),
                    ('check_out_reminder', 'Check-out Reminder'),
                    ('property_approved', 'Property Approved'),
                    ('property_rejected', 'Property Rejected'),
                    ('review_received', 'Review Received'),
                    ('commission_paid', 'Commission Paid'),
                    ('maintenance_request_created', 'Maintenance Request Created'),
                    ('maintenance_status_update', 'Maintenance Status Updated'),
                    ('maintenance_assigned', 'Maintenance Assigned'),
                    ('maintenance_comment', 'New Maintenance Comment'),
                    ('maintenance_property_update', 'Property Maintenance Update'),
                    ('maintenance_completed', 'Maintenance Completed'),
                    ('maintenance_urgent', 'Urgent Maintenance Request'),
                    ('agent_request_assigned', 'Agent Request Assigned'),
                    ('agent_request_completed', 'Agent Request Completed'),
                    ('agent_new_review', 'New Agent Review'),
                    ('agent_commission_earned', 'Commission Earned'),
                    ('agent_profile_verified', 'Agent Profile Verified'),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('booking_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('property_updates', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(
                    choices=[
                        ('booking_confirmed', 'Booking Confirmed'),
                        ('booking_cancelled', 'Booking Cancelled'),
                        ('payment_completed', 'Payment Completed'),
                        ('payment_failed', 'Payment Failed'),
                        ('check_in_reminder', 'Check-in Reminder'),
                        ('check_out_reminder', 'Check-out Reminder'),
                        ('property_approved', 'Property Approved'),
                        ('property_rejected', 'Property Rejected'),
                        ('review_received', 'Review Received'),
                        ('commission_paid', 'Commission Paid'),
                        ('maintenance_request_created', 'Maintenance Request Created'),
                        ('maintenance_status_update', 'Maintenance Status Updated'),
                        ('maintenance_assigned', 'Maintenance Assigned'),
                        ('maintenance_comment', 'New Maintenance Comment'),
                        ('maintenance_property_update', 'Property Maintenance Update'),
                        ('maintenance_completed', 'Maintenance Completed'),
                        ('maintenance_urgent', 'Urgent Maintenance Request'),
                        ('agent_request_assigned', 'Agent Request Assigned'),
                        ('agent_request_completed', 'Agent Request Completed'),
                        ('agent_new_review', 'New Agent Review'),
                        ('agent_commission_earned', 'Commission Earned'),
                        ('agent_profile_verified', 'Agent Profile Verified'),
                    ],
                    max_length=30,
                    unique=True,
                )),
                ('channel', models.CharField(
                    choices=[
                        ('email', 'Email'),
                        ('sms', 'SMS'),
                        ('push', 'Push Notification'),
                        ('in_app', 'In-App'),
                    ],
                    max_length=20,
                )),
                ('subject_template', models.CharField(blank=True, max_length=200)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
