# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_preferences_and_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('booking_confirmed', 'Booking Confirmed'),
                    ('booking_cancelled', 'Booking Cancelled'),
                    ('payment_completed', 'Payment Completed'),
                    ('payment_failed', 'Payment Failed'),
                    ('check_in_reminder', 'Check-in Reminder'),
                    ('check_out_reminder', 'Check-out Reminder'),
                    ('property_approved', 'Property Approved'),
                    ('property_rejected', 'Property Rejected'),
                    ('review_received', 'Review Received'),
                    ('review_requested', 'Review Requested'),
                    ('commission_paid', 'Commission Paid'),
                    ('maintenance_request_created', 'Maintenance Request Created'),
                    ('maintenance_status_update', 'Maintenance Status Updated'),
                    ('maintenance_assigned', 'Maintenance Assigned'),
                    ('maintenance_comment', 'New Maintenance Comment'),
                    ('maintenance_property_update', 'Property Maintenance Update'),
                    ('maintenance_completed', 'Maintenance Completed'),
                    ('maintenance_urgent', 'Urgent Maintenance Request'),
                    ('agent_request_assigned', 'Agent Request Assigned'),
                    ('agent_request_completed', 'Agent Request Completed'),
                    ('agent_new_review', 'New Agent Review'),
                    ('agent_commission_earned', 'Commission Earned'),
                    ('agent_profile_verified', 'Agent Profile Verified'),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('booking_confirmed', 'Booking Confirmed'),
                    ('booking_cancelled', 'Booking Cancelled'),
                    ('payment_completed', 'Payment Completed'),
                    ('payment_failed', 'Payment Failed'),
                    ('check_in_reminder', 'Check-in Reminder'),
                    ('check_out_reminder', 'Check-out Reminder'),
                    ('property_approved', 'Property Approved'),
                    ('property_rejected', 'Property Rejected'),
                    ('review_received', 'Review Received'),
                    ('review_requested', 'Review Requested'),
                    ('commission_paid', 'Commission Paid'),
                    ('maintenance_request_created', 'Maintenance Request Created'),
                    ('maintenance_status_update', 'Maintenance Status Updated'),
                    ('maintenance_assigned', 'Maintenance Assigned'),
                    ('maintenance_comment', 'New Maintenance Comment'),
                    ('maintenance_property_update', 'Property Maintenance Update'),
                    ('maintenance_completed', 'Maintenance Completed'),
                    ('maintenance_urgent', 'Urgent Maintenance Request'),
                    ('agent_request_assigned', 'Agent Request Assigned'),
                    ('agent_request_completed', 'Agent Request Completed'),
                    ('agent_new_review', 'New Agent Review'),
                    ('agent_commission_earned', 'Commission Earned'),
                    ('agent_profile_verified', 'Agent Profile Verified'),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
