# Generated by Django 6.0.3 on 2026-04-01 10:53

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default maintenance categories"""
    MaintenanceCategory = apps.get_model('maintenance', 'MaintenanceCategory')
    
    categories = [
        {
            'name': 'Plumbing',
            'description': 'Issues related to pipes, faucets, toilets, and water systems',
            'icon': '💧',
            'color': '#3b82f6'
        },
        {
            'name': 'Electrical',
            'description': 'Issues related to wiring, outlets, switches, and electrical systems',
            'icon': '⚡',
            'color': '#f59e0b'
        },
        {
            'name': 'HVAC',
            'description': 'Heating, ventilation, and air conditioning issues',
            'icon': '❄️',
            'color': '#06b6d4'
        },
        {
            'name': 'Appliances',
            'description': 'Issues with kitchen appliances, laundry machines, etc.',
            'icon': '🔧',
            'color': '#8b5cf6'
        },
        {
            'name': 'Structural',
            'description': 'Issues with walls, floors, ceilings, doors, and windows',
            'icon': '🏠',
            'color': '#ef4444'
        },
        {
            'name': 'Pest Control',
            'description': 'Issues with insects, rodents, and other pests',
            'icon': '🐛',
            'color': '#84cc16'
        },
        {
            'name': 'Cleaning',
            'description': 'General cleaning and maintenance requests',
            'icon': '🧹',
            'color': '#10b981'
        },
        {
            'name': 'Security',
            'description': 'Issues with locks, alarms, and security systems',
            'icon': '🔒',
            'color': '#f97316'
        },
        {
            'name': 'Landscaping',
            'description': 'Issues with lawn, garden, and outdoor areas',
            'icon': '🌿',
            'color': '#22c55e'
        },
        {
            'name': 'Other',
            'description': 'Miscellaneous maintenance issues',
            'icon': '📋',
            'color': '#6b7280'
        }
    ]
    
    for category_data in categories:
        MaintenanceCategory.objects.create(**category_data)


def reverse_default_categories(apps, schema_editor):
    """Remove default maintenance categories"""
    MaintenanceCategory = apps.get_model('maintenance', 'MaintenanceCategory')
    MaintenanceCategory.objects.filter(
        name__in=[
            'Plumbing', 'Electrical', 'HVAC', 'Appliances', 'Structural',
            'Pest Control', 'Cleaning', 'Security', 'Landscaping', 'Other'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories)
    ]
