# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260506_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(
                blank=True,
                help_text='Admin secret key for secure login',
                max_length=100,
                null=True,
            ),
        ),
    ]
