# Generated by Django 6.0.3 on 2026-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, help_text='Uganda county', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(default='Kampala', help_text='Uganda district', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='parish',
            field=models.CharField(blank=True, help_text='Uganda parish', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_county',
            field=models.CharField(blank=True, help_text='Uganda sub-county', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, help_text='Uganda village', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Uganda', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('pg', 'Paying Guest'), ('apartment', 'Apartment'), ('house', 'Independent House'), ('villa', 'Villa'), ('studio', 'Studio Apartment'), ('flat', 'Flat'), ('shared_room', 'Shared Room'), ('commercial', 'Commercial Space'), ('office', 'Office Space'), ('bedsitter', 'Bedsitter'), ('single_room', 'Single Room'), ('double_room', 'Double Room'), ('self_contained', 'Self Contained'), ('boys_quarters', "Boys' Quarters"), ('servants_quarters', "Servants' Quarters")], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='target_audience',
            field=models.CharField(choices=[('students', 'Students'), ('professionals', 'Working Professionals'), ('families', 'Families'), ('mixed', 'Mixed Audience'), ('business', 'Business Travelers'), ('expats', 'Expatriates'), ('senior_citizens', 'Senior Citizens'), ('university_students', 'University Students'), ('college_students', 'College Students'), ('interns', 'Interns'), ('nurses', 'Nurses & Medical Staff'), ('teachers', 'Teachers'), ('ngo_workers', 'NGO Workers')], default='mixed', max_length=20),
        ),
    ]
