# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_city_remove_property_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
