# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_image_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='target_audience',
            field=models.CharField(
                choices=[
                    ('students', 'Students'),
                    ('professionals', 'Working Professionals'),
                    ('families', 'Families'),
                    ('mixed', 'Mixed Audience'),
                    ('business', 'Business Travelers'),
                    ('expats', 'Expatriates'),
                    ('senior_citizens', 'Senior Citizens'),
                    ('university_students', 'University Students'),
                    ('college_students', 'College Students'),
                    ('interns', 'Interns'),
                    ('nurses', 'Nurses & Medical Staff'),
                    ('teachers', 'Teachers'),
                    ('ngo_workers', 'NGO Workers'),
                    ('public', 'Public'),
                ],
                default='mixed',
                max_length=20,
            ),
        ),
    ]
