# Generated by Django 4.2.9 on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('webhook_secret', models.TextField(blank=True)),
                ('supported_cards', models.JSONField(default=list, help_text='List of supported card types')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000000, max_digits=10)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.9, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=1500, max_digits=8)),
                ('supports_ugx', models.BooleanField(default=True, help_text='Supports UGX transactions')),
                ('supports_usd', models.BooleanField(default=True, help_text='Supports USD transactions')),
                ('supports_3ds', models.BooleanField(default=True, help_text='Supports 3D Secure')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_masked', models.CharField(max_length=20)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20)),
                ('expiry_month', models.PositiveIntegerField()),
                ('expiry_year', models.PositiveIntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('cvv_verified', models.BooleanField(default=False)),
                ('avs_verified', models.BooleanField(default=False)),
                ('three_d_secure_required', models.BooleanField(default=False)),
                ('three_d_secure_completed', models.BooleanField(default=False)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('fraud_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(default=dict)),
                ('three_d_secure_url', models.URLField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.CharField(blank=True, max_length=500)),
                ('refund_id', models.CharField(blank=True, max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='payments.Payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_cards.creditcardprovider')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_expiry_month', models.PositiveIntegerField()),
                ('card_expiry_year', models.PositiveIntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_cards.creditcardprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
