# Generated by Django 6.0.3 on 2026-03-19 07:59

from django.db import migrations, models
from django.conf import settings


def create_default_credit_card_providers(apps, schema_editor):
    """Create default credit card providers"""
    from credit_cards.models import CreditCardProvider
    
    providers_data = [
        {
            'name': 'Stripe',
            'code': 'STRIPE',
            'display_name': 'Stripe',
            'api_endpoint': 'https://api.stripe.com/v1',
            'supported_cards': ['visa', 'mastercard', 'american_express', 'discover'],
            'min_amount': 1000,
            'max_amount': 50000000,
            'transaction_fee_percentage': 2.9,
            'fixed_fee': 1500,
            'supports_ugx': True,
            'supports_usd': True,
            'supports_3ds': True,
        },
        {
            'name': 'Flutterwave',
            'code': 'FLUTTERWAVE',
            'display_name': 'Flutterwave',
            'api_endpoint': 'https://api.flutterwave.com/v3',
            'supported_cards': ['visa', 'mastercard', 'unionpay'],
            'min_amount': 1000,
            'max_amount': 20000000,
            'transaction_fee_percentage': 3.2,
            'fixed_fee': 1200,
            'supports_ugx': True,
            'supports_usd': True,
            'supports_3ds': True,
        },
        {
            'name': 'Paystack',
            'code': 'PAYSTACK',
            'display_name': 'Paystack',
            'api_endpoint': 'https://api.paystack.co',
            'supported_cards': ['visa', 'mastercard', 'unionpay'],
            'min_amount': 1000,
            'max_amount': 15000000,
            'transaction_fee_percentage': 2.5,
            'fixed_fee': 1000,
            'supports_ugx': True,
            'supports_usd': True,
            'supports_3ds': True,
        },
        {
            'name': 'DPO Uganda',
            'code': 'DPO_UGANDA',
            'display_name': 'DPO Uganda',
            'api_endpoint': 'https://secure.3gdirectpay.com',
            'supported_cards': ['visa', 'mastercard'],
            'min_amount': 2000,
            'max_amount': 10000000,
            'transaction_fee_percentage': 3.0,
            'fixed_fee': 800,
            'supports_ugx': True,
            'supports_usd': False,
            'supports_3ds': True,
        },
    ]
    
    for provider_data in providers_data:
        CreditCardProvider.objects.get_or_create(
            code=provider_data['code'],
            defaults=provider_data
        )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField()),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('webhook_secret', models.TextField(blank=True)),
                ('supported_cards', models.JSONField(default=list)),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=50000000, max_digits=10)),
                ('transaction_fee_percentage', models.DecimalField(decimal_places=2, default=2.9, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=1500, max_digits=8)),
                ('supports_ugx', models.BooleanField(default=True)),
                ('supports_usd', models.BooleanField(default=True)),
                ('supports_3ds', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_expiry_month', models.PositiveIntegerField()),
                ('card_expiry_year', models.PositiveIntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('billing_address', models.JSONField(default=dict)),
                ('billing_country', models.CharField(default='UG', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('chargeback', 'Chargeback')], default='initiated', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(default=dict)),
                ('authorization_code', models.CharField(blank=True, max_length=100)),
                ('fraud_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_3ds', models.BooleanField(default=False)),
                ('three_d_secure_url', models.URLField(blank=True)),
                ('three_d_secure_completed', models.BooleanField(default=False)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_reason', models.CharField(blank=True, max_length=500)),
                ('refund_id', models.CharField(blank=True, max_length=100)),
                ('payment', models.OneToOneField(on_delete=models.CASCADE, related_name='credit_card', to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=models.PROTECT, to='credit_cards.CreditCardProvider')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('unionpay', 'UnionPay'), ('other', 'Other')], max_length=20)),
                ('card_last_four', models.CharField(max_length=4)),
                ('card_expiry_month', models.PositiveIntegerField()),
                ('card_expiry_year', models.PositiveIntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('provider_token', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.JSONField(default=dict)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('provider', models.ForeignKey(on_delete=models.CASCADE, to='credit_cards.CreditCardProvider')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='low', max_length=20)),
                ('cvv_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('zip_code_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=100)),
                ('transactions_last_hour', models.PositiveIntegerField(default=0)),
                ('transactions_last_day', models.PositiveIntegerField(default=0)),
                ('amount_last_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_last_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=models.CASCADE, related_name='verification', to='credit_cards.CreditCardPayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_authorized', 'Payment Authorized'), ('payment_captured', 'Payment Captured'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('chargeback_received', 'Chargeback Received'), ('fraud_detected', 'Fraud Detected'), ('3ds_initiated', '3D Secure Initiated'), ('3ds_completed', '3D Secure Completed')], max_length=30)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=models.CASCADE, to='credit_cards.CreditCardProvider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='credit_cards.CreditCardPayment')),
            ],
        ),
        migrations.RunPython(create_default_credit_card_providers),
    ]
