# Generated by Django 6.0.3 on 2026-03-19 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardprovider',
            options={'ordering': ['display_name']},
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditcardprovider',
            name='supported_cards',
            field=models.JSONField(default=list, help_text='List of supported card types'),
        ),
        migrations.AlterField(
            model_name='creditcardprovider',
            name='supports_3ds',
            field=models.BooleanField(default=True, help_text='Supports 3D Secure'),
        ),
        migrations.AlterField(
            model_name='creditcardprovider',
            name='supports_ugx',
            field=models.BooleanField(default=True, help_text='Supports UGX transactions'),
        ),
        migrations.AlterField(
            model_name='creditcardprovider',
            name='supports_usd',
            field=models.BooleanField(default=True, help_text='Supports USD transactions'),
        ),
    ]
