# Generated by Django

import datetime
import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_credit_card_payments(apps, schema_editor):
    CreditCardPayment = apps.get_model('credit_cards', 'CreditCardPayment')

    for credit_payment in CreditCardPayment.objects.all():
        masked_number = getattr(credit_payment, 'card_last_four', '') or ''
        digits = ''.join(ch for ch in masked_number if ch.isdigit())
        credit_payment.card_last_four = digits[-4:] if digits else '0000'

        if not credit_payment.transaction_id:
            credit_payment.transaction_id = f"CC-{credit_payment.pk}-{uuid.uuid4().hex[:12].upper()}"

        if credit_payment.status == 'pending':
            credit_payment.status = 'initiated'

        if credit_payment.amount is None:
            payment = getattr(credit_payment, 'payment', None)
            credit_payment.amount = getattr(payment, 'amount', Decimal('0.00')) or Decimal('0.00')

        if credit_payment.fee_amount is None:
            credit_payment.fee_amount = Decimal('0.00')

        if credit_payment.net_amount is None:
            credit_payment.net_amount = credit_payment.amount - credit_payment.fee_amount

        credit_payment.save(update_fields=[
            'card_last_four',
            'transaction_id',
            'status',
            'amount',
            'fee_amount',
            'net_amount',
        ])


def backfill_saved_credit_cards(apps, schema_editor):
    SavedCreditCard = apps.get_model('credit_cards', 'SavedCreditCard')

    for saved_card in SavedCreditCard.objects.all():
        if not saved_card.provider_token:
            saved_card.provider_token = f"LEGACY-{saved_card.pk}-{uuid.uuid4().hex[:12].upper()}"

        if not saved_card.expires_at:
            saved_card.expires_at = django.utils.timezone.make_aware(
                datetime.datetime(saved_card.card_expiry_year, saved_card.card_expiry_month, 1)
            )

        saved_card.save(update_fields=['provider_token', 'expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0002_alter_creditcardprovider_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='card_number_masked',
            new_name='card_last_four',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='expiry_month',
            new_name='card_expiry_month',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='expiry_year',
            new_name='card_expiry_year',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='processed_at',
            new_name='authorized_at',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='three_d_secure_required',
            new_name='requires_3ds',
        ),
        migrations.RenameField(
            model_name='savedcreditcard',
            old_name='token',
            new_name='provider_token',
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='billing_country',
            field=models.CharField(default='UG', max_length=2),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditcardpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='billing_address',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='savedcreditcard',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='avs_verified',
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='cvv_verified',
        ),
        migrations.RemoveField(
            model_name='creditcardpayment',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='savedcreditcard',
            name='is_active',
        ),
        migrations.RunPython(backfill_credit_card_payments, migrations.RunPython.noop),
        migrations.RunPython(backfill_saved_credit_cards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='card_last_four',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='status',
            field=models.CharField(
                choices=[
                    ('initiated', 'Initiated'),
                    ('processing', 'Processing'),
                    ('authorized', 'Authorized'),
                    ('captured', 'Captured'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('cancelled', 'Cancelled'),
                    ('refunded', 'Refunded'),
                    ('chargeback', 'Chargeback'),
                ],
                default='initiated',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='creditcardpayment',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='savedcreditcard',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='savedcreditcard',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardprovider'),
        ),
        migrations.AlterField(
            model_name='savedcreditcard',
            name='provider_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='savedcreditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CreditCardVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='low', max_length=20)),
                ('cvv_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('zip_code_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=100)),
                ('transactions_last_hour', models.PositiveIntegerField(default=0)),
                ('transactions_last_day', models.PositiveIntegerField(default=0)),
                ('amount_last_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_last_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='credit_cards.creditcardpayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_initiated', 'Payment Initiated'), ('payment_authorized', 'Payment Authorized'), ('payment_captured', 'Payment Captured'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('refund_processed', 'Refund Processed'), ('chargeback_received', 'Chargeback Received'), ('fraud_detected', 'Fraud Detected'), ('3ds_initiated', '3D Secure Initiated'), ('3ds_completed', '3D Secure Completed')], max_length=30)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardprovider')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_cards.creditcardpayment')),
            ],
        ),
    ]
